{% set name = "exejs" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exejs-{{ version }}.tar.gz
  sha256: d01f5e791d26d27630b61b68ed006193fae9629d3cccba0de24fc05cd24f95bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - nodejs
test:
  imports:
    - exejs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/uliontse/exejs
  summary: Run JavaScript code from Python.
  dev_url: https://github.com/UlionTse/exejs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
