{% set name = "exejs" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exejs-{{ version }}.tar.gz
  sha256: 1f1a1b770b09bfe3a8a4739e173b9b039f11f769568593f3a0c5a065246579d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - nodejs
test:
  imports:
    - exejs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/uliontse/exejs
  summary: Run JavaScript code from Python.
  dev_url: https://github.com/UlionTse/exejs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - UlionTse
